<?php
/**
 * WP-CLI commands.
 *
 * Every setup step on this project is a scripted, re-runnable command. There is
 * no "click through the admin UI" instruction anywhere in the README, and there
 * should never be one.
 *
 * @package Noviq\Core
 */

declare(strict_types=1);

namespace Noviq\Core\Cli;

use Noviq\Core\PostTypes;
use Noviq\Core\Seed\Seeder;

defined( 'ABSPATH' ) || exit;

final class Commands {

	/**
	 * Seed the store from wp-content/plugins/noviq-core/data.
	 *
	 * Idempotent: every record is matched on a stable key (slug, SKU or term
	 * slug) and updated in place, so running this twice produces no duplicates.
	 *
	 * The data directory is generated by `node bin/build-seed-data.mjs`. Seeding
	 * the full catalog is `--full` on that script, then this command again — a
	 * data change, not a code change.
	 *
	 * ## OPTIONS
	 *
	 * [--skip-store]
	 * : Leave WooCommerce settings, pages and shipping zones alone.
	 *
	 * [--production]
	 * : Load products.production.json (PSP vial prices, stock qty). Use on the
	 *   live host only — local Docker keeps products.json dev placeholders.
	 *
	 * [--dry-run]
	 * : Report what would change without writing.
	 *
	 * ## EXAMPLES
	 *
	 *     wp noviq seed
	 *     wp noviq seed --dry-run
	 *     wp noviq seed --production --skip-store
	 *
	 * @param string[]              $args       Positional arguments.
	 * @param array<string, string> $assoc_args Flags.
	 */
	public function seed( array $args, array $assoc_args ): void {
		if ( ! class_exists( \WooCommerce::class ) ) {
			\WP_CLI::error( 'WooCommerce is not active. Activate it before seeding.' );
		}

		$seeder = new Seeder(
			isset( $assoc_args['dry-run'] ),
			isset( $assoc_args['skip-store'] ),
			isset( $assoc_args['production'] )
		);

		$seeder->run();
	}

	/**
	 * Create or update VIP creator coupons from data/{profile}/vip-coupons.json.
	 *
	 * Each code is a perpetual percent discount with no usage cap (individual
	 * use only — one coupon per cart). Idempotent
	 * on coupon code. VIP share links are root paths: /{CODE} (e.g. /LELE10).
	 * /go/{CODE} remains available for any coupon.
	 *
	 * Optional `share` fields in the JSON (title, description, image) are for
	 * Open Graph previews only and are not written to WooCommerce.
	 *
	 * ## OPTIONS
	 *
	 * [--dry-run]
	 * : Report what would change without writing.
	 *
	 * ## EXAMPLES
	 *
	 *     wp noviq seed_vip_coupons
	 *     wp noviq seed_vip_coupons --dry-run
	 *
	 * @param string[]              $args       Positional arguments.
	 * @param array<string, string> $assoc_args Flags.
	 */
	public function seed_vip_coupons( array $args, array $assoc_args ): void {
		if ( ! class_exists( \WooCommerce::class ) || ! class_exists( \WC_Coupon::class ) ) {
			\WP_CLI::error( 'WooCommerce is not active. Activate it before seeding VIP coupons.' );
		}

		$seeder = new Seeder( isset( $assoc_args['dry-run'] ), true );
		( new \Noviq\Core\Seed\VipCoupons( $seeder ) )->run();
		$seeder->success( 'VIP coupon seed complete.' );
	}

	/**
	 * Audit VIP share Open Graph readiness from vip-coupons.json.
	 *
	 * Reports each code as OK or lists missing share fields / missing image
	 * files under plugin/assets/. Read-only; does not write coupons.
	 *
	 * ## EXAMPLES
	 *
	 *     wp noviq vip_share_audit
	 *
	 * @param string[]              $args       Positional arguments.
	 * @param array<string, string> $assoc_args Flags.
	 */
	public function vip_share_audit( array $args, array $assoc_args ): void {
		$rows = \Noviq\Core\Commerce\VipCouponsRegistry::rows();
		if ( array() === $rows ) {
			\WP_CLI::warning( 'No VIP coupons found in data/{profile}/vip-coupons.json.' );
			return;
		}

		$ok     = 0;
		$issues = 0;

		foreach ( $rows as $row ) {
			if ( ! is_array( $row ) || ! isset( $row['code'] ) ) {
				continue;
			}

			$code = function_exists( 'wc_format_coupon_code' )
				? wc_format_coupon_code( (string) $row['code'] )
				: strtolower( (string) $row['code'] );

			$share  = ( isset( $row['share'] ) && is_array( $row['share'] ) ) ? $row['share'] : array();
			$missing = array();

			foreach ( array( 'creator_name', 'title', 'description', 'image' ) as $field ) {
				if ( ! isset( $share[ $field ] ) || ! is_string( $share[ $field ] ) || '' === trim( $share[ $field ] ) ) {
					$missing[] = 'share.' . $field;
				}
			}

			$image_note = '';
			if ( isset( $share['image'] ) && is_string( $share['image'] ) && '' !== trim( $share['image'] ) ) {
				$rel = ltrim( str_replace( '\\', '/', trim( $share['image'] ) ), '/' );
				if ( str_contains( $rel, '..' ) || ! is_readable( NOVIQ_CORE_PATH . 'assets/' . $rel ) ) {
					$missing[]  = 'image file';
					$image_note = ' (assets/' . $rel . ')';
				}
			}

			$default_ok = is_readable( NOVIQ_CORE_PATH . 'assets/vip/default.jpg' );

			if ( array() === $missing ) {
				\WP_CLI::log( sprintf( 'OK      %s', $code ) );
				++$ok;
			} else {
				\WP_CLI::log(
					sprintf(
						'MISSING %s — %s%s%s',
						$code,
						implode( ', ', $missing ),
						$image_note,
						$default_ok ? '' : ' [also missing assets/vip/default.jpg]'
					)
				);
				++$issues;
			}
		}

		\WP_CLI::log( '' );
		\WP_CLI::success(
			sprintf(
				'VIP share audit: %d OK, %d with gaps (fallback OG still works when share is incomplete).',
				$ok,
				$issues
			)
		);
	}

	/**
	 * Import Certificates of Analysis from data/{profile}/coas.json + PDF dir.
	 *
	 * Production-only. Creates published noviq_lot rows linked to variation SKUs
	 * and sideloads PDFs into the media library. Idempotent on lot_number and
	 * PDF filename. Does not invent lot numbers or purity — those come from the
	 * analysing lab via the manifest.
	 *
	 * Set NOVIQ_COA_DIR to the directory of PDFs (default /var/www/noviq-coa-pdfs).
	 *
	 * ## OPTIONS
	 *
	 * [--dry-run]
	 * : Report what would change without writing.
	 *
	 * ## EXAMPLES
	 *
	 *     wp noviq import_coas
	 *     wp noviq import_coas --dry-run
	 *     NOVIQ_COA_DIR=/var/www/noviq-coa-pdfs wp noviq import_coas
	 *
	 * @param string[]              $args       Positional arguments.
	 * @param array<string, string> $assoc_args Flags.
	 */
	public function import_coas( array $args, array $assoc_args ): void {
		if ( ! class_exists( \WooCommerce::class ) ) {
			\WP_CLI::error( 'WooCommerce is not active. Activate it before importing COAs.' );
		}

		if ( ! \Noviq\Core\Profile::feature( 'lots' ) ) {
			\WP_CLI::error( 'Lots are disabled for this profile.' );
		}

		$seeder = new Seeder( isset( $assoc_args['dry-run'] ), true );
		( new \Noviq\Core\Seed\ImportCoas( $seeder ) )->run();
		$seeder->success( 'COA import complete.' );
	}

	/**
	 * Delete everything the seeder creates.
	 *
	 * Products, compounds, comparisons, articles and seeded pages are removed.
	 * Orders and customers are never touched.
	 *
	 * ## OPTIONS
	 *
	 * [--yes]
	 * : Skip the confirmation prompt.
	 *
	 * @param string[]              $args       Positional arguments.
	 * @param array<string, string> $assoc_args Flags.
	 */
	public function reset( array $args, array $assoc_args ): void {
		\WP_CLI::confirm( 'Delete all seeded products, compounds, comparisons, articles and pages?', $assoc_args );

		$types   = array( 'product', 'product_variation', PostTypes::COMPOUND, PostTypes::COMPARISON, PostTypes::LOT );
		$deleted = 0;

		foreach ( $types as $type ) {
			$ids = get_posts(
				array(
					'post_type'      => $type,
					'posts_per_page' => -1,
					'post_status'    => 'any',
					'fields'         => 'ids',
				)
			);

			foreach ( $ids as $id ) {
				wp_delete_post( (int) $id, true );
				++$deleted;
			}
		}

		\WP_CLI::success( sprintf( 'Deleted %d posts.', $deleted ) );
	}

	/**
	 * Print the compliance state of the site.
	 *
	 * Checks the invariants that matter in this category: that the lot registry
	 * is empty unless real certificates were supplied, that no unsubstantiated
	 * claim is being rendered, and that the attestation gate is wired up.
	 */
	public function compliance(): void {
		\WP_CLI::log( sprintf( 'Profile:                   %s', \Noviq\Core\Profile::id() ) );

		if ( \Noviq\Core\Profile::feature( 'lots' ) ) {
			$lots = (int) wp_count_posts( PostTypes::LOT )->publish;

			\WP_CLI::log( sprintf( 'Published lots:            %d', $lots ) );
			\WP_CLI::log(
				sprintf(
					'Lot registry state:       %s',
					0 === $lots ? 'empty (expected until real COAs are supplied)' : 'populated — confirm every row came from the analysing lab'
				)
			);
		} else {
			\WP_CLI::log( 'Lot registry:              disabled for this profile' );
		}

		$claims = \Noviq\Core\Claims::all();
		$nulls  = array_keys( array_filter( $claims, static fn( $v ): bool => null === $v ) );

		\WP_CLI::log( sprintf( 'Unsubstantiated claims:   %s', implode( ', ', $nulls ) ?: '(none)' ) );
		\WP_CLI::log( '                          (these render nothing by design)' );

		$checkout = wc_get_page_id( 'checkout' );
		\WP_CLI::log(
			sprintf(
				'Checkout attestation:     %s',
				\Noviq\Core\Compliance\Attestation::uses_block_checkout()
					? 'registered on block checkout'
					: 'registered on classic checkout'
			)
		);
		\WP_CLI::log( sprintf( 'Checkout page ID:         %d', (int) $checkout ) );

		if ( \Noviq\Core\Profile::feature( 'age_gate' ) ) {
			\WP_CLI::log(
				sprintf(
					'Age gate:                 asking "%s" (copy v%s)',
					\Noviq\Core\Compliance\AgeGate::question(),
					\Noviq\Core\Compliance\AgeGate::copy_version()
				)
			);
		} else {
			\WP_CLI::log( 'Age gate:                 disabled for this profile' );
		}

		\WP_CLI::success( 'Compliance report complete.' );
	}
}
